### PR TITLE
Testing GH Actions

### PR DESCRIPTION
**Pull request by Phil-Friderici**

### CODE REVIEW

**Comment by anders-larsson** [comment]
You might need to update `.sync.yml` to ensure changes to other files remain after pdk is updated. However it seems like .sync.yml has been modified already removing some configuration that was used. This is why Gemfile and Rakefile is changed (entries from .sync.yml removed).

**Comment by Phil-Friderici** [comment]
Yepp, .sync.yml was changed by me intentionally. github_changelog_generator has broken dependencies and therefore failed :(

**Comment by anders-larsson** [comment]
Maybe we should limit ourselves to Puppet 6 and Puppet 7?

AFAIK Puppet 5 is EOL. Puppet 6 is EOL December 2022 though so we should probably test it.

**Comment by Phil-Friderici** [comment]
Yeah good advice, thanks !
I'll remove Puppet 5 to save (run) time

**Pull request merged**
